name: release
on: 
  release:
    types: [created]

jobs:
  test-before-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17.x' ]
    steps:      
    - uses: actions/checkout@master
    - name: Setup Go for use with actions
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: go test ./...
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    needs: test-before-release
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.KRATOS_TOKEN}}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.17.3.linux-amd64.tar.gz"
        project_path: "."
        binary_name: "kratos"
        extra_files: LICENSE README.md
        retry: 10
  docker:
    runs-on: ubuntu-latest
    needs: test-before-release
    steps:      
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: laghoule/kratos/kratos
        username: ${{ github.actor }}
        password: ${{ secrets.KRATOS_TOKEN }}
        registry: ghcr.io
        tag_names: true